version: '3.4'

services:

  config-server:
    build: ./config-server
    working_dir: /config-server
    volumes:
      - ./config-server:/config-server
    ports:
      - "8888:8888"
    networks:
      - my-net
    depends_on:
      - rabbitmq

  client1:
    build: ./cloud.config.client1
    working_dir: /cloud.config.client1
    volumes:
      - ./cloud.config.client1:/cloud.config.client1
    ports:
      - "8081:8081"
    networks:
      - my-net
    depends_on:
      - config-server

  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-net


networks:
  my-net:
    driver: bridge